'use client';

import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { Phone, MessageCircle } from 'lucide-react';

export default function PricingSection() {
  const categories = ['Logo', 'Web', 'Ecommerce', 'Content', 'Video', 'SMM', 'SEO'];

  const allPackages = {
    'Logo': [
      {
        h6: 'LOGO PACKAGE',
        name: 'BASIC LOGO PACKAGE',
        oldPrice: '$90.00',
        price: '$45.00',
        features: [
          '3 Custom Logo Design Concepts',
          '1 Dedicated Designer',
          '4 Revisions',
          '2 hours TAT',
          '100% Unique Design Guarantee',
          '100% Satisfaction Guarantee',
          '100% Money Back Guarantee *',
          '100% Ownership Rights',
        ],
        ribbon: 'Free Rush Delivery',
        additional: '$50 Additional For Expedited Services',
        viewDetails: 'package/Basic-Logo-Package.html',
      },
      {
        h6: 'LOGO PACKAGE',
        name: 'STARTUP LOGO PACKAGE',
        oldPrice: '$139.98',
        price: '$69.99',
        features: [
          '4 Custom Logo Design Concepts',
          'By 2 Designers',
          'Unlimited Revisions',
          '24 to 48 hours TAT',
          '100% Ownership Rights',
          '100% Satisfaction Guarantee',
          '100% Unique Design Guarantee',
          '100% Money Back Guarantee*',
        ],
        ribbon: '',
        additional: '$50 Additional For Expedited Services',
        viewDetails: 'package/Startup-Logo-Package.html',
      },
      {
        h6: 'LOGO PACKAGE',
        name: 'PROFESSIONAL LOGO PACKAGE',
        oldPrice: '$239.98',
        price: '$119.99',
        features: [
          'Unlimited Logo Design Concepts',
          'By 4 Industry Based Designers',
          'UNLIMITED Revisions',
          'FREE MS Electronic Letterhead',
          'FREE Custom Stationery Design (Letterhead, Business Card, Envelope)',
          '24 to 48 hours TAT',
          'FREE File Formats (EPS, Ai, GIF, JPEG, PSD)',
          '100% Ownership Rights',
          '100% Satisfaction Guarantee',
          '100% Unique Design Guarantee',
          '100% Money Back Guarantee',
        ],
        ribbon: 'BEST SELLER',
        additional: '$50 Additional For Expedited Services',
        viewDetails: 'package/Professional-Logo-Package.html',
      },
      {
        h6: 'LOGO PACKAGE',
        name: 'IDENTITY LOGO PACKAGE',
        oldPrice: '$339.98',
        price: '$169.99',
        features: [
          'Unlimited Logo Design Concepts by 8 Designers',
          'FREE Icon Design',
          'FREE Unlimited Revisions',
          'Turnaround time 2-3 business days',
          '1 Stationery Design Set (Business card, Letterhead, Envelope & Email Signature)',
          '100% Ownership Rights',
          '100% Satisfaction Guarantee',
          '100% Unique Design Guarantee',
          '100% Money Back Guarantee *',
        ],
        ribbon: '',
        additional: '$50 Additional For Expedited Services',
        viewDetails: 'package/Identity-Logo-Package.html',
      },
      {
        h6: 'LOGO PACKAGE',
        name: 'CORPORATE LOGO PACKAGE',
        oldPrice: '$439.98',
        price: '$219.99',
        features: [
          'UNLIMITED Logo Design Concepts',
          'By 8 Award Winning Designers',
          'Icon Design',
          'UNLIMITED Revisions',
          'Print Media',
          'Stationary Design (BusinessCard,Letterhead & Envelope)',
          'Invoice Design, Email Signature',
          'Bi-Fold Brochure (OR) 2 Sided Flyer Design',
          'Product Catalog Design',
          'Sign age Design (OR) Label Design',
          'T-Shirt Design (OR) Car Wrap Design',
          '100% Ownership Rights',
          '100% Satisfaction Guarantee',
          '100% Unique Design Guarantee',
          '100% Money Back Guarantee *',
        ],
        ribbon: '',
        additional: '$50 Additional For Expedited Services',
        viewDetails: 'package/Corporate-Logo-Package.html',
      },
      {
        h6: 'LOGO PACKAGE',
        name: 'ELITE LOGO PACKAGE',
        oldPrice: '$839.98',
        price: '$419.99',
        features: [
          'UNLIMITED Logo Design Concepts',
          'By 8 Design Artist',
          'UNLIMITED Revisions',
          '2 Stationary Design Sets',
          'FREE MS Word Letterhead',
          'Free Email Signature',
          '3 Page Custom Website',
          'Mobile Responsive',
          '2 Stock Photos',
          '2 Banner Designs',
          'jQuery Slider',
          'All Final Files Format (AI, PSD, EPS, PNG, GIF, JPG, PDF)',
          '100% Ownership Rights',
          '100% Satisfaction Guarantee',
          '100% Unique Design Guarantee',
          '100% Money Back Guarantee *',
        ],
        ribbon: '',
        additional: '$50 Additional For Expedited Services',
        viewDetails: 'package/Elite-Logo-Package.html',
      },
    ],
    'Web': [
      {
        h6: 'WEB PACKAGE',
        name: 'BASIC WEB PACKAGE',
        oldPrice: '$439.98',
        price: '$219.99',
        features: [
          '2 Stock Images',
          '3 Page Website',
          '1 jQuery Slider Banner',
          'Contact/Query Form',
          'Complete W3C Certified HTML',
          '48 to 72 hours TAT',
          'Complete Deployment',
          '100% Satisfaction Guarantee',
          '100% Unique Design Guarantee',
          '100% Money Back Guarantee *',
        ],
        ribbon: '',
        additional: '$50 Additional For Expedited Services',
        viewDetails: 'package/Basic-Web-Package.html',
      },
      {
        h6: 'WEB PACKAGE',
        name: 'STARTUP WEB PACKAGE',
        oldPrice: '$839.98',
        price: '$419.99',
        features: [
          '5 Stock Photos',
          '5 Page Website',
          '3 Banner Design',
          '1 jQuery Slider Banner',
          'FREE Google Friendly Sitemap',
          'Complete W3C Certified HTML',
          '48 to 72 hours TAT',
          '100% Satisfaction Guarantee',
          '100% Unique Design Guarantee',
          '100% Money Back Guarantee *',
          'Mobile Responsive will be Additional $200*',
          'CMS will be Additional $250*',
        ],
        ribbon: '',
        additional: '$50 Additional For Expedited Services',
        viewDetails: 'package/Startup-Web-Package.html',
      },
      {
        h6: 'WEB PACKAGE',
        name: 'PROFESSIONAL WEB PACKAGE',
        oldPrice: '$1,639.98',
        price: '$819.99',
        features: [
          '10 Unique Pages Website',
          'CMS / Admin Panel Support',
          '8 Stock images',
          '5 Banner Designs',
          '1 jQuery Slider Banner',
          'FREE Google Friendly Sitemap',
          'Complete W3C Certified HTML',
          '48 to 72 hours TAT',
          'Complete Deployment',
          '100% Satisfaction Guarantee',
          '100% Unique Design Guarantee',
          '100% Money Back Guarantee *',
          'Mobile Responsive will be Additional $200*',
        ],
        ribbon: '',
        additional: '$50 Additional For Expedited Services',
        viewDetails: 'package/Professional-Web-Package.html',
      },
      {
        h6: 'WEB PACKAGE',
        name: 'IDENTITY WEB PACKAGE',
        oldPrice: '$2,799.98',
        price: '$1,399.99',
        features: [
          'Upto 15 Unique Pages Website',
          'Conceptual and Dynamic Website',
          'Mobile Responsive',
          'Online Reservation/Appointment Tool (Optional)',
          'Online Payment Integration (Optional)',
          'Custom Forms',
          'Lead Capturing Forms (Optional)',
          'Striking Hover Effects',
          'Newsletter Subscription (Optional)',
          'Newsfeed Integration',
          'Social Media Integration',
          'Search Engine Submission',
          '5 Stock Photos',
          '3 Unique Banner Design',
          '1 jQuery Slider Banner',
          ' Complete W3C Certified HTML',
          '48 to 72 hours TAT',
          'Complete Deployment',
          '100% Satisfaction Guarantee',
          '100% Unique Design Guarantee',
          '100% Money Back Guarantee *',
        ],
        ribbon: '',
        additional: '$50 Additional For Expedited Services',
        viewDetails: 'package/identity-web-package.html',
      },
      {
        h6: 'WEB PACKAGE',
        name: 'ELITE WEB PACKAGE',
        oldPrice: '$3,599.98',
        price: '$1,799.99',
        features: [
          '15 to 20 Pages Website',
          'Custom Made, Interactive, Dynamic & High End Design',
          'Custom WP (or) Custom PHP Development',
          '1 jQuery Slider Banner',
          'Up to 10 Custom Made Banner Designs',
          '10 Stock Images',
          'Unlimited Revisions',
          'Special Hoover Effects',
          'Content Management System (CMS)',
          'Online Appointment/Scheduling/Online Ordering Integration (Optional)',
          'Online Payment Integration (Optional)',
          'Multi Lingual (Optional)',
          'Custom Dynamic Forms (Optional)',
          'Signup Area (For Newsletters, Offers etc.)',
          'Search Bar',
          'Live Feeds of Social Networks integration (Optional)',
          'Mobile Responsive',
          'FREE 5 Years Domain Name',
          'Free Google Friendly Sitemap',
          'Search Engine Submission',
          'Complete W3C Certified HTML',
          'Industry Specified Team of Expert Designers and Developers',
          'Complete Deployment',
          'Dedicated Accounts Manager',
          '100% Ownership Rights',
          '100% Satisfaction Guarantee',
          '100% Unique Design Guarantee',
          '100% Money Back Guarantee *',
        ],
        ribbon: '',
        additional: '$50 Additional For Expedited Services',
        viewDetails: 'package/elite-web-package.html',
      },
      {
        h6: 'WEB PACKAGE',
        name: 'CORPORATE WEB PACKAGE',
        oldPrice: '$6,799.98',
        price: '$3,399.99',
        features: [
          '90 Seconds 2D Explainer Video',
          'Voice - Over & Sound Effects',
          'Professional Script Writing',
          'Storyboard',
          'SEO Meta Tags',
          '15 to 20 Pages Website',
          'Custom Made, Interactive, Dynamic & High End Design',
          'Custom WP (or) Custom PHP Development',
          '1 jQuery Slider Banner',
          'Up to 10 Custom Made Banner Designs',
          '10 Stock Images',
          'Unlimited Revisions',
          'Special Hoover Effects',
          'Content Management System (CMS)',
          'Online Appointment/Scheduling/Online Ordering Integration (Optional)',
          'Online Payment Integration (Optional)',
          'Multi Lingual (Optional)',
          'Custom Dynamic Forms (Optional)',
          'Signup Area (For Newsletters, Offers etc.)',
          'Search Bar',
          'Live Feeds of Social Networks integration (Optional)',
          'Mobile Responsive',
          'FREE 5 Years Domain Name',
          'Free Google Friendly Sitemap',
          'Search Engine Submission',
          'Complete W3C Certified HTML',
          'Industry Specified Team of Expert Designers and Developers',
          'Complete Deployment',
          'Dedicated Accounts Manager',
          '100% Ownership Rights',
          '100% Satisfaction Guarantee',
          '100% Unique Design Guarantee',
          '100% Money Back Guarantee *',
        ],
        ribbon: '',
        additional: '$50 Additional For Expedited Services',
        viewDetails: 'package/corporate-web-package.html',
      },
      {
        h6: 'WEB PACKAGE',
        name: 'CUSTOMIZED WEB PORTAL',
        oldPrice: '$8,999.98',
        price: '$4,499.99',
        features: [
          'Complete Custom Design & Development',
          'Dating Portal, Job Portal, Professional Network Portal, Social Network Portal, Restaurant Portal, Medical Portal, Enterprise Portal (Any One)',
          'Unique, User Friendly, Interactive, Dynamic, High End UI Design',
          'Unlimited Banner Designs',
          'Interactive Sliding Banners',
          'Special Hover Effects',
          'Unlimited Stock Images',
          'User Signup Area',
          'Client/User Dashboard Area',
          'Custom Coding and Development',
          'Content Management System (Custom)',
          'Online Appointment/Scheduling/Online Ordering Integration (Optional)',
          'Online Payment Integration (Optional)',
          'Multi Lingual (Optional)',
          'Custom Dynamic Forms (Optional)',
          'Shopping Cart Integration (Optional)',
          'Complete Database Creation',
          'Signup Automated Email Authentication',
          'Web Traffic Analytics Integration',
          '3rd Party API Integrations',
          'Signup Area (For Newsletters, Offers etc.)',
          'Search Bar for Easy Search',
          'Live Feeds of Social Networks integration (Optional)',
          'Search Engine Submission',
          'Module-wise Architecture',
          'Extensive Admin Pane',
          'Award Winning Team of Expert Designers and Developers',
          'Complete Deployment',
          '– Value Added Services',
          'Complete Source Files',
          'Dedicated Project Manager',
          '100% Ownership Rights',
          '100% Satisfaction Guarantee',
          '100% Money Back Guarantee',
          '– Add on',
          'Professional Content/Copywriting',
          'Shopping Cart Integration',
          'Additional Professional Email ID',
        ],
        ribbon: '',
        additional: '$50 Additional For Expedited Services',
        viewDetails: 'package/customized-web-portal.html',
      },
    ],
    'Ecommerce': [
      {
        h6: 'E-COMMERCE PACKAGE',
        name: 'E-COMMERCE BASIC',
        oldPrice: '$794.00',
        price: '$397.00',
        features: [
          'Up-to 50 Products',
          'Content Management System (CMS)',
          'Mini Shopping Cart Integration',
          'Dedicated designer & developer',
          'Unlimited Revisions',
          '100% Satisfaction Guarantee',
          '100% Unique Design Guarantee',
          '100% Money Back Guarantee *',
        ],
        ribbon: '',
        additional: '$50 Additional For Expedited Services',
        viewDetails: 'package/Ecommerce-Basic-Package.html',
      },
      {
        h6: 'E-COMMERCE PACKAGE',
        name: 'E-COMMERCE STARTUP',
        oldPrice: '$1,588.00',
        price: '$794.00',
        features: [
          'Up-to 100 Products',
          'Content Management System (CMS)',
          'Mini Shopping Cart Integration',
          'Payment Module Integration',
          'Easy Product Search',
          'Dedicated designer & developer',
          'Unlimited Revisions',
          '100% Satisfaction Guarantee',
          '100% Unique Design Guarantee',
          '100% Money Back Guarantee *',
        ],
        ribbon: '',
        additional: '$50 Additional For Expedited Services',
        viewDetails: 'package/Ecommerce-Startup-Package.html',
      },
      {
        h6: 'E-COMMERCE PACKAGE',
        name: 'E-COMMERCE PROFESSIONAL',
        oldPrice: '$2,788.00',
        price: '$1,394.00',
        features: [
          'Customized Design',
          'Up-to 500 Products',
          'Content Management System (CMS)',
          'Full Shopping Cart Integration',
          'Payment Module Integration',
          'Easy Product Search',
          'Product Reviews',
          '5 Promotional Banners',
          'Team of Expert Designers & Developers',
          'Unlimited Revisions',
          '100% Satisfaction Guarantee',
          '100% Unique Design Guarantee',
          '100% Money Back Guarantee *',
        ],
        ribbon: '',
        additional: '$50 Additional For Expedited Services',
        viewDetails: 'package/Ecommerce-Professional-Package.html',
      },
      {
        h6: 'E-COMMERCE PACKAGE',
        name: 'E-COMMERCE ELITE',
        oldPrice: '$7,388.00',
        price: '$3,694.00',
        features: [
          'UNLIMITED Logo Design Concepts',
          'By 6 Award Winning Designers',
          'Icon Design',
          'UNLIMITED Revisions',
          'Print Media',
          'Stationary Design (BusinessCard,Letterhead & Envelope)',
          'Invoice Design, Email Signature',
          'Bi-Fold Brochure (OR) 2 Sided Flyer Design',
          'Product Catalog Design',
          'Sign age Design (OR) Label Design',
          'T-Shirt Design (OR) Car Wrap Design',
          'Website',
          'E-Commerce Store Design',
          'Product Detail Page Design',
          'Unique Banner Slider',
          'Featured Products Showcase',
          'Full Shopping Cart Integration',
          'Unlimited Products',
          'Unlimited Categories',
          'Product Rating & Reviews',
          'Easy Product Search',
          'Payment Gateway Integration',
          'Multi-currency Support',
          'Content Management System',
          'Cutomer Log-in Area',
          'Mobile Responsive',
          'Social Media Plugins Integration',
          'Tell a Friend Feature',
          'Social Media Pages',
          'Facebook , Twitter, YouTube, Google+ & Pinterest Page Designs',
          'Value Added Services',
          'Dedicated Account Manager',
          'Unlimited Revisions',
          'All Final File Formats',
          '100% Ownership Rights',
          '100% Satisfaction Guarantee',
          '100% Unique Design Guarantee',
          '100% Money Back Guarantee *',
        ],
        ribbon: '',
        additional: '$50 Additional For Expedited Services',
        viewDetails: 'package/Ecommerce-Elite-Package.html',
      },
    ],
    'Content': [
      {
        h6: 'CONTENT PACKAGE',
        name: 'WEB CONTENT BASIC',
        oldPrice: '$258.00',
        price: '$129.00',
        features: [
          '1 Page Professional Copywriting Service',
          'Creative & Well-Written by 1 Professional Copywriter',
          'Industry Specified Expert Copywriter',
          '300 Words Per Page',
          '5 Revisions',
          '3 to 4 Business Days Rotation',
          'According To Your Exact Requirements',
          'Proofing by our in-house experts',
          '100% Ownership Rights',
          '100% Original Content',
          '100% Approval Assurance',
          '30 Days Refund Warranty',
        ],
        ribbon: '',
        additional: '$50 Additional For Expedited Services',
        viewDetails: 'package/Web-Content-Basic-Package.html',
      },
      {
        h6: 'CONTENT PACKAGE',
        name: 'WEB CONTENT STARTER',
        oldPrice: '$1,119.00',
        price: '$499.00',
        features: [
          '5 Pages Professional Copywriting Service',
          'Creative & Well-Written by 2 Professional Copywriters',
          'Industry Specified Expert Copywriters',
          '300 Words Per Page',
          '10 Revisions',
          '5 to 7 Business Days Rotation',
          'According To Your Exact Requirements',
          'Proofing by our in-house experts',
          'FREE Meta details – With each custom page, we will provide a catchy title, keywords and page description.',
          'SEO friendly – Your keyword(s) will be placed in the title, the first & last paragraphs and throughout the web copy in a natural and fluent manner',
          '100% Ownership Rights',
          '100% Original Content',
          '100% Approval Assurance',
          '30 Days Refund Warranty',
        ],
        ribbon: '',
        additional: '$50 Additional For Expedited Services',
        viewDetails: 'package/Web-Content-Starter-Package.html',
      },
      {
        h6: 'CONTENT PACKAGE',
        name: 'WEB CONTENT PROFESSIONAL',
        oldPrice: '$2,119.00',
        price: '$849.00',
        features: [
          '10 Pages Professional Copywriting Service',
          'Creative & Well-Written by 2 Professional Copywriters',
          'Industry Specified Expert Copywriters',
          '300 Words Per Page',
          'Unlimited Revisions',
          '7 to 10 Business Days Rotation',
          'According To Your Exact Requirements',
          'Proofing by our in-house experts',
          'FREE Meta details – With each custom page, we will provide a catchy title, keywords and page description.',
          'SEO friendly – Your keyword(s) will be placed in the title, the first & last paragraphs and throughout the web copy in a natural and fluent manner',
          '100% Ownership Rights',
          '100% Original Content',
          '100% Approval Assurance',
          '30 Days Refund Warranty',
        ],
        ribbon: '',
        additional: '$50 Additional For Expedited Services',
        viewDetails: 'package/Web-Content-Professional-Package.html',
      },
      {
        h6: 'CONTENT PACKAGE',
        name: 'WEB CONTENT IDENTITY',
        oldPrice: '$4,619.00',
        price: '$1,849.00',
        features: [
          'Up to 20 Pages Professional Copywriting Service',
          'Creative & Well-Written by 3 Professional Copywriters',
          'Industry Specified Expert Copywriters',
          '300 Words Per Page',
          'Unlimited Revisions',
          '7 to 10 Business Days Rotation',
          'According To Your Exact Requirements',
          'Proofing by our in-house experts',
          'FREE Meta details – With each custom page, we will provide a catchy title, keywords and page description.',
          'SEO friendly – Your keyword(s) will be placed in the title, the first & last paragraphs and throughout the web copy in a natural and fluent manner',
          '100% Ownership Rights',
          '100% Original Content',
          '100% Approval Assurance',
          '30 Days Refund Warranty',
        ],
        ribbon: '',
        additional: '$50 Additional For Expedited Services',
        viewDetails: 'package/Web-Content-Identity-Package.html',
      },
      {
        h6: 'CONTENT PACKAGE',
        name: 'ARTICLE WRITING PACKAGE',
        oldPrice: '$298.00',
        price: '$149.00',
        features: [
          '1 Creative, Fresh & Well-Written Article',
          'By 1 Professional Copywriter',
          'Industry Specified Expert Copywriter',
          '400 Words Per Page',
          '3 to 5 Business Days Rotation',
          '5 Revisions',
          'According To Your Exact Requirements',
          'Written on Your Specified Topic/Keyword',
          'Proofing by our in-house experts',
          'Free Submission on any article marketing directories /blog (If required)',
          'SEO friendly – Your keyword(s) will be placed in the title, the first & last paragraphs and throughout the web copy in a natural and fluent manner',
          '100% Ownership Rights',
          '100% Original Content',
          '100% Approval Assurance',
          '30 Days Refund Warranty',
        ],
        ribbon: '',
        additional: '$50 Additional For Expedited Services',
        viewDetails: 'package/Article-Writing-Package.html',
      },
      {
        h6: 'CONTENT PACKAGE',
        name: 'BLOG WRITING PACKAGE',
        oldPrice: '$319.00',
        price: '$129.00',
        features: [
          '1 Creative, Fresh & Well-Written Article',
          'By 1 Professional Copywriter',
          'Industry Specified Expert Copywriter',
          '400 Words Per Page',
          '3 to 5 Business Days Rotation',
          '5 Revisions',
          'According To Your Exact Requirements',
          'Written on Your Specified Topic/Keyword',
          'Proofing by our in-house experts',
          'Free Submission on any article marketing directories /blog (If required)',
          'SEO friendly – Your keyword(s) will be placed in the title, the first & last paragraphs and throughout the web copy in a natural and fluent manner',
          '100% Ownership Rights',
          '100% Original Content',
          '100% Approval Assurance',
          '30 Days Refund Warranty',
        ],
        ribbon: '',
        additional: '$50 Additional For Expedited Services',
        viewDetails: 'package/Blog-Writing-Package.html',
      },
    ],
    'Video': [
      {
        h6: '',
        name: '2D BASIC VIDEO PACKAGE',
        oldPrice: '$659.00',
        price: '$329.00',
        features: [
          '30 Second Video',
          'Professional Script',
          'Custom Design',
          'Storyboard',
          'Custom Animation',
          'Voice – Over & Sound Effects',
          '4 weeks Delivery',
          '100% Ownership Rights',
          '100% Satisfaction Guarantee',
          '100% Money Back Guarantee',
          '100% Unique Design Guarantee',
        ],
        ribbon: '',
        additional: '$50 Additional For Expedited Services',
        viewDetails: 'package/2D-Basic-Video-Package.html',
      },
      {
        h6: '',
        name: '2D STARTUP VIDEO PACKAGE',
        oldPrice: '$1659.00',
        price: '$829.00',
        features: [
          '60 Second Video',
          'Professional Script',
          'Custom Design',
          'Storyboard',
          'Custom Animation',
          'Voice – Over & Sound Effects',
          '5 weeks Delivery',
          '100% Ownership Rights',
          '100% Satisfaction Guarantee',
          '100% Money Back Guarantee',
          '100% Unique Design Guarantee',
        ],
        ribbon: '',
        additional: '$50 Additional For Expedited Services',
        viewDetails: 'package/2D-Startup-Video-Package.html',
      },
      {
        h6: '',
        name: '2D PROFESSIONAL VIDEO PACKAGE',
        oldPrice: '$2659.00',
        price: '$1,329.00',
        features: [
          '90 Second Video',
          'Professional Script',
          'Custom Design',
          'Storyboard',
          'Custom Animation',
          'Voice – Over & Sound Effects',
          '6 weeks Delivery',
          '100% Ownership Rights',
          '100% Satisfaction Guarantee',
          '100% Money Back Guarantee',
          '100% Unique Design Guarantee',
        ],
        ribbon: '',
        additional: '$50 Additional For Expedited Services',
        viewDetails: 'package/2D-Professional-Video-Package.html',
      },
      {
        h6: '',
        name: '2D ELITE VIDEO PACKAGE',
        oldPrice: '$4,059.00',
        price: '$2,029.00',
        features: [
          '120 Second Video',
          'Professional Script',
          'Custom Design',
          'Storyboard',
          'Custom Animation',
          'Voice – Over & Sound Effects',
          '100% Ownership Rights',
          '100% Satisfaction Guarantee',
          '100% Money Back Guarantee',
          '100% Unique Design Guarantee',
        ],
        ribbon: '',
        additional: '$50 Additional For Expedited Services',
        viewDetails: 'package/2D-Elite-Video-Package.html',
      },
      {
        h6: '',
        name: '2D CORPORATE VIDEO PACKAGE',
        oldPrice: '$5,459.00',
        price: '$2,729.00',
        features: [
          '180 Second Video',
          'Professional Script',
          'Custom Design',
          'Storyboard',
          'Custom Animation',
          'Voice – Over & Sound Effects',
          '100% Ownership Rights',
          '100% Satisfaction Guarantee',
          '100% Money Back Guarantee',
          '100% Unique Design Guarantee',
        ],
        ribbon: '',
        additional: '$50 Additional For Expedited Services',
        viewDetails: 'package/2D-Corporate-Video-Package.html',
      },
      {
        h6: '',
        name: '3D BASIC VIDEO PACKAGE',
        oldPrice: '$6,459.00',
        price: '$3,229.00',
        features: [
          '30 Second Video',
          'Professional Script',
          'Custom Design',
          'Storyboard',
          'Custom Animation',
          'Voice – Over & Sound Effects',
          '100% Ownership Rights',
          '100% Satisfaction Guarantee',
          '100% Money Back Guarantee',
          '100% Unique Design Guarantee',
        ],
        ribbon: '',
        additional: '$50 Additional For Expedited Services',
        viewDetails: 'package/3D-Basic-Video-Package.html',
      },
      {
        h6: '',
        name: '3D STARTUP VIDEO PACKAGE',
        oldPrice: '$8,909.00',
        price: '$4,459.00',
        features: [
          '60 Second Video',
          'Professional Script',
          'Custom Design',
          'Storyboard',
          'Custom Animation',
          'Voice – Over & Sound Effects',
          '100% Ownership Rights',
          '100% Satisfaction Guarantee',
          '100% Money Back Guarantee',
          '100% Unique Design Guarantee',
        ],
        ribbon: '',
        additional: '$50 Additional For Expedited Services',
        viewDetails: 'package/3D-Startup-Video-Package.html',
      },
      {
        h6: '',
        name: '3D PROFESSIONAL VIDEO PACKAGE',
        oldPrice: '$10,909.00',
        price: '$5,459.00',
        features: [
          '90 Second Video',
          'Professional Script',
          'Custom Design',
          'Storyboard',
          'Custom Animation',
          'Voice – Over & Sound Effects',
          '100% Ownership Rights',
          '100% Satisfaction Guarantee',
          '100% Money Back Guarantee',
          '100% Unique Design Guarantee',
        ],
        ribbon: '',
        additional: '$50 Additional For Expedited Services',
        viewDetails: 'package/3D-Professional-Video-Package.html',
      },
      {
        h6: '',
        name: '3D ELITE VIDEO PACKAGE',
        oldPrice: '$13,309.00',
        price: '$6,659.00',
        features: [
          '90 Second Video',
          'Professional Script',
          'Custom Design',
          'Storyboard',
          'Custom Animation',
          'Voice – Over & Sound Effects',
          '100% Ownership Rights',
          '100% Satisfaction Guarantee',
          '100% Money Back Guarantee',
          '100% Unique Design Guarantee',
        ],
        ribbon: '',
        additional: '$50 Additional For Expedited Services',
        viewDetails: 'package/3D-Elite-Video-Package.html',
      },
    ],
    'SMM': [
      {
        h6: 'Social Media Marketing',
        name: 'STARTUP PACKAGE',
        oldPrice: '$699.98',
        price: '$349.99',
        features: [
          '3 postings per week (per network) Facebook + Twitter + Instagram + Google+ ',
          'Content Creation ',
          'Business Page Optimization ',
          'Social Media Strategy (Overview) ',
          'Facebook Likes Campaign ',
          'Monthly Progress report ',
          'Copy Writing',
        ],
        ribbon: '',
        additional: '$50 Additional For Expedited Services',
        viewDetails: '',
      },
      {
        h6: 'Social Media Marketing',
        name: 'SCALING PACKAGE',
        oldPrice: '$1,399.98',
        price: '$699.99',
        features: [
          'Copywriting & Visual designs ',
          'Business Page Optimization ',
          'Ad Campaign Management ',
          'Spam monitoring ',
          'Monthly Progress report ',
          '5 postings per week Facebook + Twitter + Instagram + Google+ ',
          'Reputation Management ',
          'Social Account Setup ',
          'Content Creation ',
          'Social Media Listening ',
          'Query and comments reply',
        ],
        ribbon: '',
        additional: '$50 Additional For Expedited Services',
        viewDetails: '',
      },
      {
        h6: 'Social Media Marketing',
        name: 'VENTURE PACKAGE',
        oldPrice: '$2,399.98',
        price: '$1,199.99',
        features: [
          'Copywriting & Visual designs ',
          'Business Page Optimization ',
          'Ad Campaign Management ',
          'Spam monitoring ',
          '6 postings per week Facebook + Twitter + Instagram + Google+ ',
          'Reputation Management ',
          'Social Account Setup ',
          'Content Creation ',
          'Social Media Hearing ',
          'Query and comments reply',
        ],
        ribbon: '',
        additional: '$50 Additional For Expedited Services',
        viewDetails: '',
      },
    ],
    'SEO': [
      {
        h6: 'SEO Packages',
        name: 'BASIC SEO PACKAGES',
        oldPrice: '$1,999.98',
        price: '$999.99',
        features: [
          'Prior Analysis',
          'Business Analysis',
          'Consumer Analysis',
          'Competitor Analysis',
          '15 Selected Keywords Targeting',
          '15 Pages Keyword Targeted',
          'Webpage Optimization',
          'Meta Tags Creation',
          'Keyword Optimization',
          'Image Optimization',
          'Inclusion of anchors',
          'Tracking & Analysis',
          'Google Analytics Installation',
          'Google Webmaster Installation',
          'Call To Action Plan',
          'Creation of Sitemaps',
          'Reporting',
          'Monthly Reporting ',
          'Recommendation ',
          'Email Support',
          'Phone Support',
          'Off Page Optimization',
          'Social Bookmarking',
          'Slide Share Marketing ',
          'Forums/FAQ’s',
          'Link Building',
          'Directory Submission',
          'Local Business Listings ',
        ],
        ribbon: '',
        additional: '$50 Additional For Expedited Services',
        viewDetails: '',
      },
      {
        h6: 'SEO Packages',
        name: 'PREMIUM SEO PACKAGES',
        oldPrice: '$2,999.98',
        price: '$1499.99',
        features: [
          'Prior Analysis ',
          'Business Analysis',
          'Consumer Analysis ',
          'Competitor Analysis ',
          '30 Selected Keywords Targeting ',
          '30 Pages Keyword Targeted',
          'Webpage Optimization ',
          'Meta Tags Creation',
          'Keyword Optimization ',
          'Image Optimization ',
          'Inclusion of anchors',
          'Tracking & Analysis ',
          'Google Places Inclusions',
          'Google Analytics Installation',
          'Google Webmaster Installation ',
          'Call To Action Plan ',
          'Creation of Sitemaps',
          'Reporting ',
          'Monthly Reporting ',
          'Recommendation ',
          'Email Support ',
          'Phone Support',
          'Off Page Optimization ',
          'Social Bookmarking',
          'Slide Share Marketing ',
          'Forums/FAQ’s ',
          'Link Building ',
          'Directory Submission ',
          'Local Business Listings',
        ],
        ribbon: '',
        additional: '$50 Additional For Expedited Services',
        viewDetails: '',
      },
      {
        h6: 'SEO Packages',
        name: 'PLATINUM SEO PACKAGES',
        oldPrice: '$3,999.98',
        price: '$1999.99',
        features: [
          'Prior Analysis ',
          'Business Analysis',
          'Consumer Analysis ',
          'Competitor Analysis ',
          '70 Selected Keywords Targeting ',
          '50 Pages Keyword Targeted',
          'Webpage Optimization ',
          'Meta Tags Creation',
          'Keyword Optimization ',
          'Image Optimization ',
          'Inclusion of anchors Tags ',
          'Inclusion of anchors Indexing Modifications',
          'Tracking & Analysis ',
          'Google Places Inclusions',
          'Google Analytics Installation',
          'Google Webmaster Installation ',
          'Call To Action Plan ',
          'Creation of Sitemaps',
          'Reporting ',
          'Monthly Reporting ',
          'Recommendation ',
          'Email Support ',
          'Phone Support',
          'Off Page Optimization ',
          'Social Bookmarking',
          'Slide Share Marketing ',
          'Forums/FAQ’s ',
          'Link Building ',
          'Directory Submission ',
          'Local Business Listings',
          'Blog Content Creation',
          'Local SEO',
        ],
        ribbon: '',
        additional: '$50 Additional For Expedited Services',
        viewDetails: '',
      },
    ],
  };

  const [currentTab, setCurrentTab] = useState('Logo');

  return (
    <section className="py-24 lg:py-32 bg-black">
      <div className="max-w-7xl mx-auto px-6 lg:px-8">

        {/* Tabs */}
        <ul className="flex flex-wrap justify-center gap-4 mb-12">
          {categories.map((tab) => (
            <li
              key={tab}
              onClick={() => setCurrentTab(tab)}
              className={`px-6 py-3 rounded-lg cursor-pointer text-gray-300 font-medium uppercase tracking-wide 
                ${currentTab === tab ? 'bg-gradient-to-r from-orange-500 to-pink-500 text-white shadow-lg' : 'bg-gray-800 hover:bg-gray-700'}`}
            >
              {tab}
            </li>
          ))}
        </ul>

        {/* Packages Grid */}
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
          {allPackages[currentTab].map((pkg, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, y: 40 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: index * 0.1 }}
              viewport={{ once: true }}
              className="relative p-8 bg-gray-900 bg-opacity-50 backdrop-blur-sm rounded-2xl border border-gray-800 hover:bg-gray-800 hover:bg-opacity-70 transition-all duration-300"
            >
              {/* Ribbon */}
              {pkg.ribbon && (
                <div className="absolute -top-4 -left-4 px-4 py-1 text-xs font-bold text-white uppercase tracking-wider bg-gradient-to-r from-red-600 to-orange-600 rotate-[-45deg] shadow-lg">
                  {pkg.ribbon}
                </div>
              )}

              {/* h6 */}
              <h6 className="text-sm font-semibold text-orange-400 uppercase">{pkg.h6}</h6>

              {/* Name */}
              <h3 className="mt-2 text-xl font-bold text-white uppercase">
                {pkg.name}
              </h3>

              {/* Price */}
              <div className="mt-4 flex items-center gap-2">
                <span className="text-lg text-gray-500 line-through">{pkg.oldPrice}</span>
                <span className="text-3xl font-bold text-white">{pkg.price}</span>
              </div>

              {/* Features – Scrollable */}
              <div className="mt-6 max-h-36 overflow-y-auto scrollbar-thin scrollbar-thumb-gray-700 scrollbar-track-gray-900">
                <ul className="space-y-2 text-gray-300 text-sm">
                  {pkg.features.map((feature, i) => (
                    <li key={i} className={feature.toLowerCase().includes('heading') ? 'font-bold text-white mt-4' : ''}>
                      {feature}
                    </li>
                  ))}
                </ul>
              </div>

              {/* Order Now */}
              <a
                href={pkg.getFreeConsultancy || 'GetFreeConsultancy.html'}
                className="mt-8 block text-center px-6 py-3 bg-gradient-to-r from-green-500 to-teal-500 text-white font-bold rounded-lg hover:shadow-xl transition-all"
              >
                ORDER NOW
              </a>

              {/* Additional */}
              <p className="mt-4 text-sm text-gray-400 text-center">
                {pkg.additional}
              </p>

              {/* View Details */}
              <a href={pkg.viewDetails} className="block text-center text-sm text-orange-400 hover:text-orange-300 transition-colors">
                VIEW DETAILS
              </a>

              {/* Actions */}
              <div className="mt-4 flex justify-center gap-4 text-sm text-gray-400">
                <a href="tel:(571) 561-8937" className="flex items-center gap-1 hover:text-orange-400">
                  <Phone className="w-4 h-4" />
                  (765) 203-1409 ext. 800
                </a>
              </div>

              {/* Inclusive */}
              <span className="block text-center text-xs text-gray-500 mt-2">
                Inclusive of GST <small>*</small>
              </span>
            </motion.div>
          ))}
        </div>

      </div>
    </section>
  );
}